name: client_ledger
description: "A client transaction tracking application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.3
  # Database
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.15
  path: ^1.8.3
  # Functional programming
  dartz: ^0.10.1
  # Equality
  equatable: ^2.0.5
  # Dependency injection
  get_it: ^7.6.0
  sqflite: ^2.4.1
  uuid: ^4.5.1
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.8.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.5   # MUST BE HERE (devDependencies)

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
